/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RedirectImport } from './routes/redirect'
import { Route as UsersLayoutImport } from './routes/users/layout'
import { Route as DashboardLayoutImport } from './routes/dashboard/layout'
import { Route as IndexImport } from './routes/index'
import { Route as UsersIndexImport } from './routes/users/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as AuthIndexImport } from './routes/auth/index'
import { Route as AboutIndexImport } from './routes/about/index'
import { Route as DashboardReposIndexImport } from './routes/dashboard/repos/index'
import { Route as DashboardGistsIndexImport } from './routes/dashboard/gists/index'

// Create/Update Routes

const RedirectRoute = RedirectImport.update({
  id: '/redirect',
  path: '/redirect',
  getParentRoute: () => rootRoute,
} as any)

const UsersLayoutRoute = UsersLayoutImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRoute,
} as any)

const DashboardLayoutRoute = DashboardLayoutImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UsersIndexRoute = UsersIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersLayoutRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRoute,
} as any)

const AboutIndexRoute = AboutIndexImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardReposIndexRoute = DashboardReposIndexImport.update({
  id: '/repos/',
  path: '/repos/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)

const DashboardGistsIndexRoute = DashboardGistsIndexImport.update({
  id: '/gists/',
  path: '/gists/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutImport
      parentRoute: typeof rootRoute
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersLayoutImport
      parentRoute: typeof rootRoute
    }
    '/redirect': {
      id: '/redirect'
      path: '/redirect'
      fullPath: '/redirect'
      preLoaderRoute: typeof RedirectImport
      parentRoute: typeof rootRoute
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutIndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/users/': {
      id: '/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexImport
      parentRoute: typeof UsersLayoutImport
    }
    '/dashboard/gists/': {
      id: '/dashboard/gists/'
      path: '/gists'
      fullPath: '/dashboard/gists'
      preLoaderRoute: typeof DashboardGistsIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/repos/': {
      id: '/dashboard/repos/'
      path: '/repos'
      fullPath: '/dashboard/repos'
      preLoaderRoute: typeof DashboardReposIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
  }
}

// Create and export the route tree

interface DashboardLayoutRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardGistsIndexRoute: typeof DashboardGistsIndexRoute
  DashboardReposIndexRoute: typeof DashboardReposIndexRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardGistsIndexRoute: DashboardGistsIndexRoute,
  DashboardReposIndexRoute: DashboardReposIndexRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

interface UsersLayoutRouteChildren {
  UsersIndexRoute: typeof UsersIndexRoute
}

const UsersLayoutRouteChildren: UsersLayoutRouteChildren = {
  UsersIndexRoute: UsersIndexRoute,
}

const UsersLayoutRouteWithChildren = UsersLayoutRoute._addFileChildren(
  UsersLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/users': typeof UsersLayoutRouteWithChildren
  '/redirect': typeof RedirectRoute
  '/about': typeof AboutIndexRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/users/': typeof UsersIndexRoute
  '/dashboard/gists': typeof DashboardGistsIndexRoute
  '/dashboard/repos': typeof DashboardReposIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/redirect': typeof RedirectRoute
  '/about': typeof AboutIndexRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/users': typeof UsersIndexRoute
  '/dashboard/gists': typeof DashboardGistsIndexRoute
  '/dashboard/repos': typeof DashboardReposIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/users': typeof UsersLayoutRouteWithChildren
  '/redirect': typeof RedirectRoute
  '/about/': typeof AboutIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/users/': typeof UsersIndexRoute
  '/dashboard/gists/': typeof DashboardGistsIndexRoute
  '/dashboard/repos/': typeof DashboardReposIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/users'
    | '/redirect'
    | '/about'
    | '/auth'
    | '/dashboard/'
    | '/users/'
    | '/dashboard/gists'
    | '/dashboard/repos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/redirect'
    | '/about'
    | '/auth'
    | '/dashboard'
    | '/users'
    | '/dashboard/gists'
    | '/dashboard/repos'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/users'
    | '/redirect'
    | '/about/'
    | '/auth/'
    | '/dashboard/'
    | '/users/'
    | '/dashboard/gists/'
    | '/dashboard/repos/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
  UsersLayoutRoute: typeof UsersLayoutRouteWithChildren
  RedirectRoute: typeof RedirectRoute
  AboutIndexRoute: typeof AboutIndexRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  UsersLayoutRoute: UsersLayoutRouteWithChildren,
  RedirectRoute: RedirectRoute,
  AboutIndexRoute: AboutIndexRoute,
  AuthIndexRoute: AuthIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard",
        "/users",
        "/redirect",
        "/about/",
        "/auth/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard/layout.tsx",
      "children": [
        "/dashboard/",
        "/dashboard/gists/",
        "/dashboard/repos/"
      ]
    },
    "/users": {
      "filePath": "users/layout.tsx",
      "children": [
        "/users/"
      ]
    },
    "/redirect": {
      "filePath": "redirect.tsx"
    },
    "/about/": {
      "filePath": "about/index.tsx"
    },
    "/auth/": {
      "filePath": "auth/index.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx",
      "parent": "/dashboard"
    },
    "/users/": {
      "filePath": "users/index.tsx",
      "parent": "/users"
    },
    "/dashboard/gists/": {
      "filePath": "dashboard/gists/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/repos/": {
      "filePath": "dashboard/repos/index.tsx",
      "parent": "/dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
